### ISSUE TITLE
Loop doesn't work

### ISSUE THREAD

**Issue by Azzinoth224** [Kylemc1413/PracticePlugin#3]
It just keeps going after the red marker.

**Comment by Kylemc1413** [comment]
Thanks for the report, will be fixed in next version of the mod on BeatMods hopefully

**Comment by Kylemc1413** [comment]
Should now be fixed in 4.8.6 that is approved on BeatMods

**Comment by Azzinoth224** [comment]
Thank you, it works. You're awesome!
